### ISSUE TITLE
使用本文公开的权重，未复现出论文结果

### ISSUE THREAD

**Issue by Rachel-kk** [mingcv/YTMT-Strategy#10]
您好！
我将已公开的权重下载到本地，并按照论文提到的测试集（real20、SIR2）上进行测试。非常遗憾，我没有复现出本文实验结果。
由此怀疑是我的数据集与论文不一致，但缺乏相关信息，制作出与论文一致的数据集，可否提供相关帮助。

非常感谢！

**Comment by Rachel-kk** [comment]
早上好，
按照你的回复，我从GitHub上将裁剪过的real20下载到本地，并进行实验。real20的PSNR/SSIM与论文的不一致，会比论文中的指标偏高，请问论文的实验数据是否GitHub上的权重（ytmt_uct_sirs_68_077_00595364.pt ）测试出来的？另外我在[SIR2]数据集的指标会比论文低，该数据集直接从官网下来的，未做任何处理。现我将[SIR2]数据集和测试时所用的命令提供，帮忙看看是否数据集问题。非常感谢！


测试命令：
CUDA_VISIBLE_DEVICES=0 python test_sirs.py --inet ytmt_ucs_old  --model twostage_ytmt_model --name ytmt_uct_sirs_test --hyper --if_align  --resume --icnn_path ./checkpoint/ytmt_uct_sirs_68_077_00595364.pt









在 2023-03-22 21:15:51，"Qiming Hu" ***@***.***> 写道：

你好，我们将real20测试数据集resize到了一个较小的尺度以便能够在当前的设备上进行推理，这一数据集在当前仓库的release中就能够下载到，SIR2数据集并没有进行额外的处理。关于训练数据集，同样也是使用我们在README中所链接VOC数据集和real数据以及使用我们在sirs_dataset.py所提供的的CEILDataset即可，并无其他的额外数据引入，数据的resize和增强在数据集文件中也都有定义。如仍有问题，欢迎通过邮件的方式给我们发送您所使用的测试图像以及具体的测试命令。

**Comment by Rachel-kk** [comment]
你好
按照你的回复，我从GitHub上将裁剪过的real20下载到本地，并进行实验。real20的PSNR/SSIM与论文的不一致，会比论文中的指标偏高，请问论文的实验数据是否GitHub上的权重（ytmt_uct_sirs_68_077_00595364.pt ）测试出来的？另外我在[SIR2]数据集的指标会比论文低，该数据集直接从官网下来的，未做任何处理。现我将[SIR2]数据集和测试时所用的命令提供，帮忙看看是否数据集问题。非常感谢！


测试命令：
CUDA_VISIBLE_DEVICES=0 python test_sirs.py --inet ytmt_ucs_old  --model twostage_ytmt_model --name ytmt_uct_sirs_test --hyper --if_align  --resume --icnn_path ./checkpoint/ytmt_uct_sirs_68_077_00595364.pt









在 2023-03-22 21:15:51，"Qiming Hu" ***@***.***> 写道：

你好，我们将real20测试数据集resize到了一个较小的尺度以便能够在当前的设备上进行推理，这一数据集在当前仓库的release中就能够下载到，SIR2数据集并没有进行额外的处理。关于训练数据集，同样也是使用我们在README中所链接VOC数据集和real数据以及使用我们在sirs_dataset.py所提供的的CEILDataset即可，并无其他的额外数据引入，数据的resize和增强在数据集文件中也都有定义。如仍有问题，欢迎通过邮件的方式给我们发送您所使用的测试图像以及具体的测试命令。

**Comment by mingcv** [comment]
你好，首先感谢你的细致复现。按照本仓库提供的测试指标的计算方式和权重，数值结果确实会有一定偏差（real20测得比论文偏高，SIR^2上的PSNR略低，SSIM略高），您可以以下图中提供的指标为准。如您实在介意则可以使用我们的训练代码重新对模型进行训练，并采用不同的随机数种子进行多次实验取指标的平均值。如您需要性能更强的模型，欢迎关注我们对本工作的更新和后序工作。
![image](https://user-images.githubusercontent.com/31566437/227221163-7448d273-9603-401f-968e-b81f6eeb5aba.png)

**Comment by mingcv** [comment]
Since there are no further questions, we close this issue. If there are any other questions, please continue the discussion.
