### ISSUE TITLE
Checkpoint (.pt) not found for Reflection Separation

### ISSUE THREAD

**Issue by TARUSHREE** [mingcv/YTMT-Strategy#11]
Hello, 
Sorry, the Google Drive link for Single Image Reflection Separation doesn't contain a '.pt' file.
Can you please provide access to the pre-trained '.pt' model file for Testing or guide on the next steps on how to run the model on test images?
Thanks!

**Comment by mingcv** [comment]
I'm sorry, but this seems the '.pt' file.
![image](https://user-images.githubusercontent.com/31566437/231760977-d8e4ea53-580c-4d96-ac23-50b31e5bfd07.png)

**Comment by mingcv** [comment]
I'll close this issue as it seems that there is no further question.
