### ISSUE TITLE
may be  sir2 dataset was changed

### ISSUE THREAD

**Issue by dongshenhan** [mingcv/YTMT-Strategy#13]
can you send me the wild bechmark dataset about sir2? ?which have 55 images......   i just  found the wildscences folder which have 109 images   in sir2 datasets。。。。  it makes me very confused...........thank you

**Comment by dongshenhan** [comment]
my email  is  838176404@qq.com  or  han-0129@khu.ac.kr.....   thanks  ~~~万分感谢

**Comment by dongshenhan** [comment]
is it 55 sences?

**Comment by dongshenhan** [comment]
because every image have groundtruth。。。。

**Comment by mingcv** [comment]
The full training&testing datasets have been sent to your @khu.ac.kr email. Please check it ;)
