### ISSUE TITLE
Run custom image, always cuda out of memory

### ISSUE THREAD

**Issue by Learningm** [mingcv/YTMT-Strategy#14]
I follow https://github.com/mingcv/YTMT-Strategy/issues/9 to run my custom image, but always faced the CUDA out of memory error.

My image is 3840x2160, and I resize it to 1920 x 1080. It still comes the CUDA out of memory error.

960x540 size is ok, but it's too small, I watch nvidia-smi and found the gpu memory peak achieve 73G and stable at 35G at this image size.

How can i use larger image?

**Comment by mingcv** [comment]
Sorry for the late response. If you are simply using the reflection decomposition model in the project, you can take a look at our new work [DSRNet](https://github.com/mingcv/DSRNet#trained-weights). We have opened up a lighter model DSRNet_ S (with only 9.41M parameters), so it should not be so easy to burst the CUDA memory.

**Comment by mingcv** [comment]
Once we have time, we will provide lighter model designs and blockwise processing of ultra-resolution images for both works and try to use all the data we can obtain as much as possible to improve the generalization performance of the model. Welcome to continue following our repository.

**Comment by Learningm** [comment]
> Sorry for the late response. If you are simply using the reflection decomposition model in the project, you can take a look at our new work [DSRNet](https://github.com/mingcv/DSRNet#trained-weights). We have opened up a lighter model DSRNet_ S (with only 9.41M parameters), so it should not be so easy to burst the CUDA memory.

Thanks for reply. 
I found DSRNet some days ago and I tried to train large resolution images using it but still encountering the out of memory error. Looking forward to ultra-resolution image supporting.

**Comment by mingcv** [comment]
> > Sorry for the late response. If you are simply using the reflection decomposition model in the project, you can take a look at our new work [DSRNet](https://github.com/mingcv/DSRNet#trained-weights). We have opened up a lighter model DSRNet_ S (with only 9.41M parameters), so it should not be so easy to burst the CUDA memory.
> 
> Thanks for reply. I found DSRNet some days ago and I tried to train large resolution images using it but still encountering the out of memory error. Looking forward to ultra-resolution image supporting.

We do not recommend that the model be trained on large-resolution images directly. Images are desired to be divided into patches for better stability during training.

**Comment by Learningm** [comment]
> > > Sorry for the late response. If you are simply using the reflection decomposition model in the project, you can take a look at our new work [DSRNet](https://github.com/mingcv/DSRNet#trained-weights). We have opened up a lighter model DSRNet_ S (with only 9.41M parameters), so it should not be so easy to burst the CUDA memory.
> > 
> > 
> > Thanks for reply. I found DSRNet some days ago and I tried to train large resolution images using it but still encountering the out of memory error. Looking forward to ultra-resolution image supporting.
> 
> We do not recommend that the model be trained on large-resolution images directly. Images are desired to be divided into patches for better stability during training.

Currently, I need to run it(YTMT or DSRNet) on the large-resolution image. How can I fix the out of memory error?

**Comment by mingcv** [comment]
> > > > Sorry for the late response. If you are simply using the reflection decomposition model in the project, you can take a look at our new work [DSRNet](https://github.com/mingcv/DSRNet#trained-weights). We have opened up a lighter model DSRNet_ S (with only 9.41M parameters), so it should not be so easy to burst the CUDA memory.
> > > 
> > > 
> > > Thanks for reply. I found DSRNet some days ago and I tried to train large resolution images using it but still encountering the out of memory error. Looking forward to ultra-resolution image supporting.
> > 
> > 
> > We do not recommend that the model be trained on large-resolution images directly. Images are desired to be divided into patches for better stability during training.
> 
> Currently, I need to run it(YTMT or DSRNet) on the large-resolution image. How can I fix the out of memory error?

If you only need to do inference on large-resolution images, I recommend using the DSRNet_S and resizing the images to a suitable size. If this still cannot meet your requirements, you can cut down the width and the number of blocks of the dsrnet_s, and then retrain it on the patchified images of your own dataset.
