### ISSUE TITLE
Could you send me the paper? thanks!  My email is zyr@mail.ustc.edu.cn

### ISSUE THREAD

**Issue by zhuyr97** [mingcv/YTMT-Strategy#2]
My email is zyr@mail.ustc.edu.cn

**Comment by XGuoTJU** [comment]
You can find the arXiv version at https://arxiv.org/pdf/2110.10546.pdf

**Comment by XGuoTJU** [comment]
> My email is [zyr@mail.ustc.edu.cn](mailto:zyr@mail.ustc.edu.cn)

You can find the arXiv version at https://arxiv.org/pdf/2110.10546.pdf
