### ISSUE TITLE
image reflection task traininng weights not find?

### ISSUE THREAD

**Issue by JiHaobo1999** [mingcv/YTMT-Strategy#5]
Sorry, I can't find training weights two_stage_xxx, Would you upload the file again??

**Comment by mingcv** [comment]
The problem has been fixed in README.md, as follows:

#### Testing 
```python test_sirs.py --inet ytmt_ucs_old --model twostage_ytmt_model --name ytmt_uct_sirs_test --hyper --if_align --resume --icnn_path ./checkpoints/ytmt_uct_sirs/ytmt_uct_sirs_68_077_00595364.pt```

*Note: "ytmt_ucs_old" is only for our provided checkpoint, and please change it as "ytmt_ucs" when you train our model by yourself, since it is a refactorized verison for a better view.*
