### ISSUE TITLE
CUDA vram allocation issue

### ISSUE THREAD

**Issue by davidgaddie** [mingcv/YTMT-Strategy#6]
Hi,

I've been trying to run the reflection test code, but I get this error:
RuntimeError: CUDA out of memory. Tried to allocate 15.66 GiB (GPU 0; 22.20 GiB total capacity; 16.09 GiB already allocated; 2.68 GiB free; 17.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I'm running on an A10G GPU on AWS. I suspect that maybe the dataset is incorrect as each image in the dataset I have is around 800MB.  If that's the case can I please be directed to the correct repository for the read20_420 images?

Thanks so much,

David

**Comment by mingcv** [comment]
https://github.com/mingcv/YTMT-Strategy/releases/download/data/real20_420.zip

**Comment by mingcv** [comment]
We made a new release. You can access the data by [this link](https://github.com/mingcv/YTMT-Strategy/releases/download/data/real20_420.zip).
