### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by davidgaddie** [mingcv/YTMT-Strategy#7]
Hi,

I have been trying to experiment with the model but I'm having trouble finding the correct datasets for testing.  The Sirs2 dataset in the provided link doesn't have the images set up with the naming conventions used in the script.  Could you please direct me to the correct data sets for testing and training? Is there a separate repository that you have used?

Thanks so much,

David

**Comment by mingcv** [comment]
The structure of the training data: 
![image](https://user-images.githubusercontent.com/31566437/204511220-e36d402d-b50e-4d1b-9138-743495d712be.png)

The structure of the testing data: 
![image](https://user-images.githubusercontent.com/31566437/204511836-b98f51cb-4bd8-498b-8241-6d4fe37a0aab.png)

If the above illustration still cannot solve your problem, please provide an e-mail address and I will send you the organized datasets needed.

**Comment by davidgaddie** [comment]
Hi,

Thanks so much for offering to help with the datasets. I am having trouble locating the "nature" dataset.  My email address is david@the-colony.com. I would greatly appreciate the organized datasets.

Thanks again,

David

**Comment by mingcv** [comment]
Having sent the full dataset.

**Comment by mursalin-asj** [comment]
Could you please send me the organized datasets? email address: mursalinir@gmail.com
Thanks in advance.

**Comment by mingcv** [comment]
> Could you please send me the organized datasets? email address: [mursalinir@gmail.com](mailto:mursalinir@gmail.com) Thanks in advance.

Sent.

**Comment by dongshenhan** [comment]
Could you please send me the organized datasets? email address: han-0129@khu.ac.kr      .Thanks in advance.

**Comment by dongshenhan** [comment]
Could you please send me the sir2 windsences datasets which have 55images? email address: [han-0129@khu.ac.kr](mailto:han-0129@khu.ac.kr) .Thanks in advance.

**Comment by daeing** [comment]
@mingcv Dear author, I met the same question about SIR2 dataset, Could you please send me this dataset? Many thanks!

**Comment by daeing** [comment]
> SIR2

My email address is 1551178638@qq.com, Many thanks.

**Comment by daeing** [comment]
> @mingcv Dear author, I met the same question about SIR2 dataset, Could you please send me this dataset? Many thanks!

Sorry, Would you mind send me the whole dataset? I run the code, when do eval on real20 dataset, run out of memory occured.
RuntimeError: CUDA out of memory. Tried to allocate 30.89 GiB (GPU 0; 79.35 GiB total capacity; 31.48 GiB already allocated; 28.92 GiB free; 48.87 GiB reserved in total by PyTorch). But my gpu's memory is lagger than 2080ti...

**Comment by mingcv** [comment]
In case of similar questions, the full dataset used by YTMT can be accessed via [this link](https://drive.google.com/file/d/1hFZItZAzAt-LnfNj-2phBRwqplDUasQy/view).
