### ISSUE TITLE
About Training Details

### ISSUE THREAD

**Issue by DUT-CSJ** [mingcv/YTMT-Strategy#8]
Hello, thank you for sharing your wonderful work. I have some question about the triaining details. 
It says the training epoch is 120 in your paper but the epoch is set to 60 in YTMT-Strategy/options/net_options/train_options.py. 
Moreover, the best model in your paper is YTMT-UCT which need two stages training. Can you provide the training settings of the YTMT-UCT (epoch, batchsize...)?
Look forward to your reply!

**Comment by mingcv** [comment]
Q: It says the training epoch is 120 in your paper but the epoch is set to 60 in YTMT-Strategy/options/net_options/train_options.py.
A: The training epoch is manually set in the `train_sirs.py` file as 120 and the training process is scheduled following this. 

Q: The best model in your paper is YTMT-UCT which needs two stages of training. Can you provide the training settings of the YTMT-UCT (epoch, batch size...)?
A: We train YTMT-UCS for 120 epochs (using `train_sirs.py`), select the model with the best performance on evaluation datasets, and then use its weights to initiate the two-stage model  (using `train_sirs_twostage.py`), selecting the model with the best performance.

**Comment by DUT-CSJ** [comment]
> Q: It says the training epoch is 120 in your paper but the epoch is set to 60 in YTMT-Strategy/options/net_options/train_options.py. A: The training epoch is manually set in the `train_sirs.py` file as 120 and the training process is scheduled following this.
> 
> Q: The best model in your paper is YTMT-UCT which needs two stages of training. Can you provide the training settings of the YTMT-UCT (epoch, batch size...)? A: We train YTMT-UCS for 120 epochs (using `train_sirs.py`), select the model with the best performance on evaluation datasets, and then use its weights to initiate the two-stage model (using `train_sirs_twostage.py`), selecting the model with the best performance.

Understand, thank you!
